name: Build and run
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc]
    steps:
    - name: Compile and run
      env:
        compiler_name: ${{ matrix.compiler }}
      run: |
        $compiler_name hello.c -o hello
        ./hello
