name: Build and run

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - name: Compile and run
      env:
        CC: ${{ matrix.compiler }}
      run: |
        $CC hello.c -o hello
        ./hello
